INSERT INTO spi_page_position (page_id, code, name) VALUES
(8, 'fin_plan_finance_user_id', 'Ansprechpartner für Rückfragen zum Finanzplan'),
(8, 'fin_plan_bank_details_id', 'Bankverbindung'),
(8, 'fin_plan_employee_is_umlage', 'Umlage 1'),
(8, 'fin_plan_employee_group_id', 'Entgeltgruppe'),
(8, 'fin_plan_employee_remuneration_level_id', 'Entgeltstufe'),
(8, 'fin_plan_employee_other', 'Sonstiges'),
(8, 'fin_plan_employee_cost_per_month_brutto', 'Kosten pro Monat (AN-Brutto)'),
(8, 'fin_plan_employee_month_count', 'Geplante Monate im Projekt'),
(8, 'fin_plan_employee_hours_per_week', 'Arbeitsstunden pro Woche'),
(8, 'fin_plan_employee_have_annual_bonus', 'Jahressonderzahlungen'),
(8, 'fin_plan_employee_have_additional_provision_vwl', 'Zusatzversorgung (VWL)'),
(8, 'fin_plan_employee_have_supplementary_pension', 'Zusatzversorgung (betriebl. Altersversorgung)'),
(8, 'fin_plan_school_rate', 'Stellenanteil'),
(8, 'fin_plan_school_month_count', 'Monat'),
(8, 'fin_plan_school_overhead_cost', 'Regiekosten'),
(8, 'fin_plan_association_name', 'Name (Berufsgenossenschaftsbeiträge)'),
(8, 'fin_plan_association_sum', 'Beitrag (Berufsgenossenschaftsbeiträge)'),
(8, 'fin_plan_revenue_description', 'Sonstige Einnahmen'),
(8, 'fin_plan_revenue_sum', 'Beitrag (Sonstige Einnahmen)');