ALTER TABLE `spi_page` ADD COLUMN `page_code` VARCHAR(45) NOT NULL AFTER `code`;
UPDATE `spi_page` SET `page_code` = 'users' WHERE `id` = '1'; 
UPDATE `spi_page` SET `page_code` = 'user-roles' WHERE `id` = '2'; 
UPDATE `spi_page` SET `page_code` = 'hints' WHERE `id` = '3'; 
UPDATE `spi_page` SET `page_code` = 'performers' WHERE `id` = '4'; 
UPDATE `spi_page` SET `page_code` = 'schools' WHERE `id` = '5'; 
UPDATE `spi_page` SET `page_code` = 'districts' WHERE `id` = '6'; 
UPDATE `spi_page` SET `page_code` = 'finance-source' WHERE `id` = '7'; 
UPDATE `spi_page` SET `page_code` = 'requests' WHERE `id` = '8'; 
UPDATE `spi_page` SET `page_code` = 'dashboard' WHERE `id` = '9';
UPDATE `spi_page` SET `page_code` = 'bank-details' WHERE `id` = '10'; 
UPDATE `spi_page` SET `page_code` = 'page-position' WHERE `id` = '11'; 
UPDATE `spi_page` SET `page_code` = 'performer-document' WHERE `id` = '12'; 
UPDATE `spi_page` SET `page_code` = 'request-status' WHERE `id` = '13'; 
UPDATE `spi_page` SET `page_code` = 'school-type' WHERE `id` = '14'; 
UPDATE `spi_page` SET `page_code` = 'projects' WHERE `id` = '15'; 
UPDATE `spi_page` SET `page_code` = 'audit' WHERE `id` = '16'; 
UPDATE `spi_page` SET `page_code` = 'document-templates' WHERE `id` = '18'; 
UPDATE `spi_page` SET `page_code` = 'email-templates' WHERE `id` = '19'; 
UPDATE `spi_page` SET `page_code` = 'page' WHERE `id` = '20'; 
UPDATE `spi_page` SET `page_code` = 'project-type' WHERE `id` = '21'; 
UPDATE `spi_page` SET `page_code` = 'document-template-type' WHERE `id` = '22'; 
UPDATE `spi_page` SET `page_code` = 'document-template-placeholder' WHERE `id` = '23'; 
UPDATE `spi_page` SET `page_code` = 'request-school-concept' WHERE `id` = '24'; 
UPDATE `spi_page` SET `page_code` = 'request-school-goal' WHERE `id` = '26'; 
UPDATE `spi_page` SET `page_code` = 'request-school-finance' WHERE `id` = '27'; 
UPDATE `spi_page` SET `page_code` = 'remuneration-level' WHERE `id` = '28'; 
UPDATE `spi_page` SET `page_code` = 'request-financial-group' WHERE `id` = '29'; 
UPDATE `spi_page` SET `page_code` = 'request-prof-association' WHERE `id` = '30';  
UPDATE `spi_page` SET `page_code` = 'request-user' WHERE `id` = '31';
INSERT INTO `spi_page` (`id`, `code`, `page_code`, `name`, `is_system`) VALUES ('32', 'index', 'index', 'Index', '1');
INSERT INTO `spi_page` (`id`, `code`, `page_code`, `name`, `is_system`) VALUES ('33', 'forgot-password', 'forgot-password', 'Forgot-password','1' );
INSERT INTO `spi_page` (`id`, `code`, `page_code`, `name`, `is_system`) VALUES ('34', 'reset-password', 'reset-password', 'Reset-password', '1');
ALTER TABLE `spi_page` ADD COLUMN `is_without_login` TINYINT(1) DEFAULT 0 NOT NULL AFTER `is_system`;
UPDATE `spi_page` SET `is_without_login` = '1' WHERE `id` = '32'; 
UPDATE `spi_page` SET `is_without_login` = '1' WHERE `id` = '33';
UPDATE `spi_page` SET `is_without_login` = '1' WHERE `id` = '34';