INSERT INTO `spi_document_template_placeholder` (`name`, `text`, `is_email`, `document_id`) VALUES ('URL', 'Request url', '1', '4');
INSERT INTO `spi_document_template_placeholder` (`name`, `text`, `is_email`, `document_id`) VALUES ('REQUEST_CODE', 'kennziffer', '1', '4');
INSERT INTO `spi_document_template_placeholder` (`name`, `text`, `is_email`, `document_id`) VALUES ('PART', 'entwicklungsziele', '1', '4');
INSERT INTO `spi_document_template_placeholder` (`name`, `text`, `is_email`, `document_id`) VALUES ('COMMENT', 'reason', '1', '4');
INSERT INTO `spi_document_template_placeholder` (`name`, `text`, `is_email`, `document_id`) VALUES ('DATE', 'email date/time', '1', '4');

INSERT INTO `spi_document_template_placeholder` (`name`, `text`, `is_email`, `document_id`) VALUES ('URL', 'Request url', '1', '2');
INSERT INTO `spi_document_template_placeholder` (`name`, `text`, `is_email`, `document_id`) VALUES ('REQUEST_CODE', 'kennziffer', '1', '2');
INSERT INTO `spi_document_template_placeholder` (`name`, `text`, `is_email`, `document_id`) VALUES ('DATE', 'email date/time', '1', '2');

INSERT INTO `spi_document_template_placeholder` (`name`, `text`, `is_email`, `document_id`) VALUES ('URL', 'Request url', '1', '3');
INSERT INTO `spi_document_template_placeholder` (`name`, `text`, `is_email`, `document_id`) VALUES ('REQUEST_CODE', 'kennziffer', '1', '3');
INSERT INTO `spi_document_template_placeholder` (`name`, `text`, `is_email`, `document_id`) VALUES ('DATE', 'email date/time', '1', '3');

UPDATE `spi_email_template` SET `text`='Ihr Antrag mit der Kennziffer {REQUEST_CODE} ist noch nicht foerderfaehig.<br> Die entsprechenden Anmerkungen finden Sie im Antrag unter {url}<br> <br> Mit freundlichen Gruessen<br>  <br> Stiftung SPI<br> Programmagentur \"Jugendsozialarbeit an Berliner Schulen\"<br> Schicklerstrasse 5-7<br> 10179 Berlin<br>  <br> [FON] +49(0)30 2888 496-0<br> [FAX] +49(0)30 2888 496-20<br>  <br> www.spi-programmagentur.de<br> programmagentur@stiftung-spi.de<br>  <br> Stiftung SPI<br> Sozialpaedagogisches Institut Berlin \"Walter May\"<br> rechtsfaehige Stiftung des privaten Rechts<br> Muellerstr. 74, 13349 Berlin<br> Vorstandsvorsitzende/Direktorin: Dr. Birgit Hoppe<br>  <br> www.stiftung-spi.de<br> info@stiftung-spi.de<br>  <br> [FON] +49(0)30 459 793-0<br> [FAX] +49(0)30 459 793-66<br>' WHERE `id`='4';
UPDATE `spi_email_template` SET `text`='<p><span style=\"background-color: rgb(255, 255, 0);\">&lt;%= @greeting %&gt;</span><br> <br> Ihr förderfähiger Antrag mit der Kennziffer <font color=\"#FF0000\"><span style=\"background-color: inherit;\">&lt;%= @kennziffer %&gt;  </span></font>wird der Senatsverwaltung zur Bewilligung vorgelegt.<br> Sowie uns die Bewilligung der Senatsverwaltung vorliegt, werden wir Sie ueber das weitere Vorgehen in Kenntnis setzen.<br> <br><b> Mit freundlichen</b> <b>Grüßen</b><br>  <br> <font color=\"#085294\">Stiftung SPI<br> Programmagentur \"Jugendsozialarbeit an Berliner Schulen\"<br> Schicklerstrasse 5-7<br> 10179 Berlin</font><br>  <br> [FON] +49(0)30 2888 496-0<br> [FAX] +49(0)30 2888 496-20<br>  <br><br><u><a target=\"_blank\" href=\"www.programmagentur@stiftung-spi.de\">programmagentur@stiftung-spi.de</a></u><br>  <br> Stiftung SPI<br> Sozialpädagogisches Institut Berlin \"Walter May\"<br> rechtsfaehige Stiftung des privaten Rechts<br> Müllerstr. 74, 13349 Berlin<br> Vorstandsvorsitzende/Direktorin: Dr. Birgit Hoppe<br>  <br> www.stiftung-spi.de<br> info@stiftung-spi.de<br>  <br> [FON] +49(0)30 459 793-0<br> [FAX] +49(0)30 459 793-66<br></p> ' WHERE `id`='2';
UPDATE `spi_email_template` SET `text`='<span style=\"background-color: inherit;\">&lt;%= @greeting %&gt;ööööö<br> <br> Ihr Antrag mit der Kennziffer &lt;%= @kennziffer %</span>&gt; wurde von der Senatsverwaltung bewilligt. Bitte loggen Sie sich in die Programmdatenbank ein (https://spider.stiftung-spi.de), drucken Sie den <font color=\"#FF0000\"><b>Antrag</b> <b>EINMAL</b></font> und den <b><span style=\"background-color: inherit;\"><font color=\"#FF0000\">Fördervertrag ZWEIMAL</font></span></b> aus. Unterschreiben Sie <span style=\"background-color: inherit;\"><font color=\"#FF0000\"><b>ALLE DREI</b></font></span> Exemplare und senden Sie diese (und falls noch nicht geschehen mit den entsprechenden Anlagen) bitte an die Programmagentur.<br> <br> Mit freundlichen Grüßen<br>  <br> Stiftung SPI<br> Programmagentur \"Jugendsozialarbeit an Berliner Schulen\"<br> Schicklerstrasse 5-7<br> 10179 Berlin<br>  <br> [FON] +49(0)30 2888 496-0<br> [FAX] +49(0)30 2888 496-20<br>  <br> www.spi-programmagentur.de<br> programmagentur@stiftung-spi.de<br>  <br> Stiftung SPI<br> Sozialpaedagogisches Institut Berlin \"Walter May\"<br> rechtsfaehige Stiftung des privaten Rechts<br> Muellerstr. 74, 13349 Berlin<br> Vorstandsvorsitzende/Direktorin: Dr. Birgit Hoppe<br>  <br> www.stiftung-spi.de<br> info@stiftung-spi.de<br>  <br> [FON] +49(0)30 459 793-0<br> [FAX] +49(0)30 459 793-66<br> ' WHERE `id`='3';